apiVersion: phylake.io/v1alpha1
kind: Cluster
metadata:
    name: my-cluster
spec:
    tenant: my-tenant
    configuration:
        description: Phylake showcase
        geographicLocation: Azure/germanywestcentral
        production: true
        disablePRFeedback: false
    policies:
        path: /policies
